config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'pages#index', as: 'home'

	resources :articles, only: [:update, :create]
  get '/research', to: 'topics#research_index', as: 'research'
  get '/news', to: 'topics#news_index', as: 'news'
  resources :topics, only: [:create, :update, :destroy]
  resources :search_terms, only: [:create, :destroy]

  resources :users, only: [:create, :update]
  get '/new_account', to: 'users#new', as: 'new_account'
  get '/my_account', to: 'users#show', as: 'my_account'
  get '/edit_account', to: 'users#edit', as: 'edit_account'
  get '/forgot_password', to: 'users#forgot_password', as: 'forgot_password'
  post '/forgot_password', to: 'users#forgot_password'
  get '/reset_password/:token', to: 'users#reset_password', as: 'reset_password'
  post '/reset_password', to: 'users#reset_password'
  get '/reset_password_confirmation', to: 'users#reset_password_confirmation', as: 'reset_password_confirmation'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get 'active', to: 'sessions#active'
  get 'timeout', to: 'sessions#timeout'

  # Error routes
  get "/404", to: "errors#error_404"
  get "/422", to: "errors#error_422"
  get "/500", to: "errors#error_500"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :topics
  has_many :api_queries

  validates_presence_of :username, :email, :time_zone
  validates :password, length: { minimum: 8 }, if: :password_required?
  validates_uniqueness_of :email, :username

  def enforce_password_validation
    @enforce_password_validation = true
  end

  def todays_query_count(type)
    date = Time.now.in_time_zone(self.time_zone).strftime("%F")
    if self.api_queries.where(date: date, query_type: type).length == 0
      return 0
    else
      return self.api_queries.where(date: date, query_type: type).first.query_count
    end
  end

  def add_query(type)
    date = Time.now.in_time_zone(self.time_zone).strftime("%F")
 
    if self.todays_query_count(type) == 0
      ApiQuery.create(user_id: self.id, date: date, query_type: type, query_count: 1)
    else
      query_count = self.todays_query_count(type)
      self.api_queries.where(date: date, query_type: type).first.update(query_count: query_count + 1)
    end
  end

  def set_token
    update token: SecureRandom.urlsafe_base64
  end

  def remove_token
    update token: nil 
  end

  def to_param
    token ? token : id.to_s
  end

  private

  def password_required?
    @enforce_password_validation || password.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_login, only: [:new, :create, :forgot_password, :reset_password, :reset_password_confirmation]
  before_action :require_login, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Your account has been created, please log in."
      redirect_to login_path
    else
      render :new
    end
  end

  def show
    @user = helpers.current_user  
  end

  def edit
    @user = helpers.current_user   
  end

  def update
    @user = User.find(params[:id])
    if @user != helpers.current_user
      flash[:danger] = "You can only edit your own information."
      redirect_to my_account_path
    elsif !@user.authenticate(params[:user][:password])
      @user.username = params[:user][:username]
      @user.email = params[:user][:email]
      @user.time_zone = params[:user][:time_zone]
      @user.errors.add(:password, "is incorrect.")
      render :edit
    elsif @user.update(user_params)
      flash[:success] = "Your account has been updated."
      redirect_to my_account_path
    else
      render :edit 
    end
  end

  def forgot_password
    if request.get?
      render :forgot_password
    elsif request.post?
      @user = User.find_by(email: params[:email])

      if @user
        @user.set_token
        @url = reset_password_url(@user)
        UserMailer.reset_password(@user, @url).deliver
        redirect_to reset_password_confirmation_path
      else
        flash[:danger] = "No user matches the email address you entered."
        redirect_to forgot_password_path
      end
    end
  end

  def reset_password
    token = params[:token] || params[:user][:token]
    @user = User.find_by(token: token)  

    if request.get?
      render :reset_password
    elsif request.post?
      @user.password = params[:user][:password]
      if @user.save
        @user.remove_token
        flash[:success] = "Your password has been updated, please log in."
        redirect_to login_path
      else
        render :reset_password
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :time_zone, :password)
  end
end

app/views/users/edit.html.haml
.container.my-4
  %h1.mb-4.pb-2.border-bottom.border-3.border-dark= "Edit Account"
  .row.justify-content-between
    .col-md-5
      = render 'shared/errors', resource: @user
      = form_for(@user) do |f|
        .mb-3
          = f.label :username, class: "form-label"
          = f.text_field :username, class: "form-control mb-3"
          = f.label :email, class: "form-label"
          = f.text_field :email, class: "form-control mb-3"
          = f.label :time_zone, "Time Zone", class: "form-label"
          = f.time_zone_select :time_zone, nil, {}, class: "form-select mb-3"
          = f.label :password, "Current Password", class: "form-label"
          = f.text_field :password, class: "form-control mb-3", type: "password"
          = f.submit "Update", class: "btn btn-primary"
    .col-md-5
      = image_tag "compass.png", alt: "compass", class: "img-fluid"
= render 'shared/info_modal_main'        

app/views/users/forgot_password.html.haml
.container.my-4
  %h1.mb-4.border-bottom.border-3.border-dark.pb-2= "Forgot Password"
  .row.justify-content-between
    .col-md-5
      %h5= "A link to reset your password will be sent to you."
      = form_tag '/forgot_password' do
        .mb-3
          %label.form-label(for="email")= "Email"
          %input.form-control#email(name="email")
        %button.btn.btn-primary(type="submit")= "Send Link"
    .col-md-5
      = image_tag "compass.png", alt: "compass", class: "img-fluid"
= render 'shared/info_modal_main'
          

app/views/users/new.html.haml
.container.my-4
  %h1.mb-4.pb-2.border-bottom.border-3.border-dark= "Create Account"
  .row.justify-content-between
    .col-md-5
      = render 'shared/errors', resource: @user
      = form_for @user do |f|
        .mb-3
          = f.label :email, "Email", class: "form-label"
          = f.text_field :email, class: "form-control", type: "email"
        .mb-3
          = f.label :username, "Username", class: "form-label"
          = f.text_field :username, class: "form-control"
        .mb-3
          = f.label :time_zone, "Time Zone", class: "form-label"
          = f.time_zone_select :time_zone, nil, {}, class: "form-select mb-3"
        .mb-3
          = f.label :password, "Password", class: "form-label"
          = f.text_field :password, class: "form-control", type: "password"
        = f.submit "Create Account", class: "btn btn-primary"
    .col-md-5
      = image_tag "compass.png", alt: "compass", class: "img-fluid"
= render 'shared/info_modal_main'    

app/views/users/reset_password.html.haml
.container.my-4
  %h1.mb-4.border-bottom.border-3.border-dark.pb-2= "Reset Password"
  .row.justify-content-between
    .col-md-5
      = render 'shared/errors', resource: @user
      = form_tag '/reset_password' do
        .mb-3
          %label.form-label(for="user[password]")= "New Password"
          %input.password.form-control#password(name="user[password]" type="password")
          %input(type="hidden" name="user[token]" value="#{@user.token}")
        %button.btn.btn-primary(type="submit")= "Reset Password"
= render 'shared/info_modal_main'

app/views/users/reset_password_confirmation.html.haml
.container.my-4
  %h1.mb-4.border-bottom.border-3.border-dark.pb-2= "Reset Password Confirmation"
  .row.justify-content-between
    .col-md-5
      %h5= "A link to reset your password has been sent to the email you provided."
    .col-md-5
      = image_tag "compass.png", alt: "compass", class: "img-fluid"
= render 'shared/info_modal_main'

app/views/users/show.html.haml
.container.my-4
  %h1.mb-4.border-bottom.border-3.border-dark.pb-2= "My Account"
  .row.justify-content-between
    .col-md-5
      = link_to "Edit Details", edit_account_path, class: "btn btn-primary mb-4"
      %h5.mb-3= "Username: #{@user.username}"
      %h5.mb-3= "Email: #{@user.email}"
      %h5.mb-3= "Time Zone: #{@user.time_zone}"
    .col-md-5
      = image_tag "compass.png", alt: "compass", class: "img-fluid"
= render 'shared/info_modal_main' 