config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'pages#index', as: 'home'

	resources :articles, only: [:update, :create]
  get '/research', to: 'topics#research_index', as: 'research'
  get '/news', to: 'topics#news_index', as: 'news'
  resources :topics, only: [:create, :update, :destroy]
  resources :search_terms, only: [:create, :destroy]

  resources :users, only: [:create, :update]
  get '/new_account', to: 'users#new', as: 'new_account'
  get '/my_account', to: 'users#show', as: 'my_account'
  get '/edit_account', to: 'users#edit', as: 'edit_account'
  get '/forgot_password', to: 'users#forgot_password', as: 'forgot_password'
  post '/forgot_password', to: 'users#forgot_password'
  get '/reset_password/:token', to: 'users#reset_password', as: 'reset_password'
  post '/reset_password', to: 'users#reset_password'
  get '/reset_password_confirmation', to: 'users#reset_password_confirmation', as: 'reset_password_confirmation'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get 'active', to: 'sessions#active'
  get 'timeout', to: 'sessions#timeout'

  # Error routes
  get "/404", to: "errors#error_404"
  get "/422", to: "errors#error_422"
  get "/500", to: "errors#error_500"
end

app/views/shared/_article.html.haml
%h2= "Summary"
%p= article.summary
= form_for(article) do |f|
  .mb-3
    = f.text_area :notes, class: "form-control", rows: "10"
.row.gy-3.justify-content-evenly.justify-content-md-start
  .col-auto
    %button.btn.btn-primary{ form: "edit_article_#{article.id}" }= "Save Notes"
  - if article.status == "new"
    .col-auto
      = form_for(article) do |f|
        = f.hidden_field(:status, value: "saved")
        = f.submit "Save For Later", class: "btn btn-primary"
  - if article.status == "new" || article.status == "saved"
    .col-auto
      = form_for(article) do |f|
        = f.hidden_field(:status, value: "read")
        = f.submit "Mark As Read", class: "btn btn-primary"
  - if article.status == "read"
    .col-auto
      = form_for(article) do |f|
        = f.hidden_field(:status, value: "saved")
        = f.submit "Mark Unread", class: "btn btn-primary"
  .col-auto
    %button.btn.btn-primary{type: "button", data: { bs: { toggle: "modal", target: "#notInterestedArticle-#{article.id}" } } }= "Not Interested"
    .modal{ id: "notInterestedArticle-#{article.id}", tabindex: "-1" }
      .modal-dialog
        .modal-content
          .modal-body
            %p= "Are you sure you want to mark <em>#{article.title}</em> as 'Not Interested'? You will not see this article again.".html_safe
            .row.gy-3
              .col-auto
                = form_for(article) do |f|
                  = f.hidden_field(:status, value: "not interested")
                  = f.submit "Not Interested", class: "btn btn-dark"
              .col-auto
                %button.btn.btn-dark{ data: { bs: { dismiss: "modal" } } }= "Cancel"
  .col-auto
    %a.btn.btn-primary{ href: article.url, role: "button"}= "Read Full Article"

app/views/shared/_coming_soon.html.haml
.h1.text-center.my-4= "This page is coming soon."
.container.w-75
  = image_tag "compass.png", alt: "compass", class: "img-fluid"

app/views/shared/_errors.html.haml
- if resource.errors.full_messages.length > 0
  .alert.alert-danger
    %p= "Please fix the following errors:"
    %ul
    - resource.errors.full_messages.each do |msg|
      %li= msg

app/views/shared/_info_modal_main.html.haml
.modal#infoModal{ tabindex: "-1", aria: { labelledby: "infoModalLabel", hidden: "true" } }
  .modal-dialog
    .modal-content
      .modal-header
        %h4.modal-title.text-dark#infoModalLabel= "About InfoCompass"
        %button.btn-close{ type: "button", data: { bs: { dismiss: "modal" } }, aria: { label: "Close" } }
      .modal-body
        %p.fs-5.mb-3.text-dark= "- InfoCompass is a website that helps you stay up to date on the things you care about."
        %p.fs-5.mb-3.text-dark= "- It is divided into 2 sections: Research Topics and News."
        %p.fs-5.mb-3.text-dark= "- Only the Research Topics section is functional right now, but the News section is coming soon!"
        %p.fs-5.mb-3.text-dark= "- Enter a topic that you're interested in and the relevant API's will be queried to check if there is a new article to show you."
        %p.fs-5.mb-3.text-dark= "- This website is still a work in progress, but I hope you find it useful."
        %p.fs-5.mb-3.text-dark= "- The source code is available #{link_to "here", "https://github.com/Calvin0125/info_compass"} if you're curious.".html_safe

app/views/shared/_info_modal_news.html.haml
.modal#infoModal{ tabindex: "-1", aria: { labelledby: "infoModalLabel", hidden: "false" } }
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        .modal-title.h4.text-dark#infoModalLabel= "About News Page"
        %button.btn-close{ type: "button", data: { bs: { dismiss: "modal" } }, aria: { label: "Close" } }
      .modal-body
        %p.fs-5.mb-3.text-dark= "- On this page you can add up to 25 news topics."
        %p.fs-5.mb-3.text-dark= "- You can request new news articles up to 25 times per day."
        %p.fs-5.mb-3.text-dark= "- When you create a topic, news articles are automatically requested."
        %p.fs-5.mb-3.text-dark= "- The 25 most recent articles will appear in the 'new' section of each topic every day."
        %p.fs-5.mb-3.text-dark= "- You will see up to 100 articles if there are that many published today. This is to ensure that you don't miss any new articles."
        %p.fs-5.mb-3.text-dark= "- The 'new' section is automatically refreshed each time you add or delete a search term."
        %p.fs-5.mb-3.text-dark= "- You can save the articles for later, mark them as read or not interested, or take notes about them."        
        %p.fs-5.mb-3.text-dark= "- If you see older articles appearing in the 'new' section, then you have read or saved all of the newest articles and the algorithm is finding older ones so there is always something you haven't seen before."
        %p.fs-5.mb-3.text-dark= "- Click the <i class='bi bi-question-circle mx-2 h4'></i> to see this message again.".html_safe

app/views/shared/_info_modal_research.html.haml
.modal#infoModal{ tabindex: "-1", aria: { labelledby: "infoModalLabel", hidden: "false" } }
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        .modal-title.h4.text-dark#infoModalLabel= "About Research Page"
        %button.btn-close{ type: "button", data: { bs: { dismiss: "modal" } }, aria: { label: "Close" } }
      .modal-body
        %p.fs-5.mb-3.text-dark= "- On this page you can add up to 25 research topics."
        %p.fs-5.mb-3.text-dark= "- Every 24 hours, the arXiv API is queried with the search terms you provide."
        %p.fs-5.mb-3.text-dark= "- arXiv contains nearly 2 million scholarly articles in various academic fields."
        %p.fs-5.mb-3.text-dark= "- The 10 most recent articles will appear in the 'new' section of each topic every day."
        %p.fs-5.mb-3.text-dark= "- You will see up to 50 articles if they were published yesterday (added to arXiv today). This is to ensure that you don't miss any new articles."
        %p.fs-5.mb-3.text-dark= "- The 'new' section is automatically refreshed each time you add or delete a search term."
        %p.fs-5.mb-3.text-dark= "- You can save the articles for later, mark them as read or not interested, or take notes about them."        
        %p.fs-5.mb-3.text-dark= "- If you see older articles appearing in the 'new' section, then you have read or saved all of the newest articles and the algorithm is finding older ones so there is always something you haven't seen before."
        %p.fs-5.mb-3.text-dark= "- Click the <i class='bi bi-question-circle mx-2 h4'></i> to see this message again.".html_safe

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  .row(class="alert alert-#{name} alert-dismissible")
    = content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String)
    %button.me-3.btn-close(type="button" data-bs-dismiss="alert")

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  - if logged_in?
    = link_to "InfoCompass", research_path, class: "text-light mx-3 display-6"
    %button.navbar-toggler.me-2#navbarToggler(type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation")
      %span.navbar-toggler-icon
    .collapse.navbar-collapse#navbarContent
      %ul.navbar-nav.d-flex.align-items-center.w-100
        %li.nav-item.dropdown.me-4.ms-3
          %a.nav-link.dropdown-toggle.h5#accountDropdownLink(href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false")= "Welcome, #{current_user.username}"
          %ul.dropdown-menu.dropdown-menu-dark(aria-labelledby="accountDropdownLink")
            %li
              = link_to("My Account", my_account_path, class: "dropdown-item h5")
            %li
              = link_to("Sign Out", logout_path, method: :delete, class: "dropdown-item h5")
        %li.nav-item
          = link_to "Research", research_path, class: "nav-link h5 ms-3 ms-md-0 ms-lg-4"
        %li.nav-item
          = link_to "News", news_path, class: "nav-link h5 ms-3 ms-md-0 ms-lg-4"
        %li.nav-item.ms-md-auto.me-lg-3.ms-3
          %i.nav-link.h3.bi.bi-question-circle.bg-dark{ type: "button", data: { bs: { toggle: "modal", target: "#infoModal" } } }
  - else
    = link_to "InfoCompass", home_path, class: "text-light mx-3 display-6"
    %ul.navbar-nav.d-flex.ms-auto
      %li.nav-item.me-3
        %i.nav-link.h3.bi.bi-question-circle.bg-dark{ type: "button", data: { bs: { toggle: "modal", target: "#infoModal" } } }

app/views/shared/_news_article_headers.html.haml
.row= article.title
.row.mt-3= article.source
.row.mt-3.text-muted= "#{article.date_published} at #{article.pretty_time_published}"

app/views/shared/_no_new_research_articles_modal.html.haml
%button.btn.btn-primary.mt-3{ data: { bs: { toggle: "modal", target: "#noNewResearchArticlesModal" } } }= "Get New Articles"
.modal#noNewResearchArticlesModal{ tabindex: "-1", aria: { hidden: "true" } }
  .modal-dialog
    .modal-content
      .modal-header
        %button.btn-close{ type: "button", data: { bs: { dismiss: "modal" } }, aria: { label: "Close" } }
      .modal-body
        %p= "You already have all of today's newest articles, you can request more research articles once you have fewer than 10 in your new articles queue."
       

app/views/shared/_research_article.html.haml
%h2= "Summary"
%p= article.summary
= form_for(article) do |f|
  .mb-3
    = f.text_area :notes, class: "form-control", rows: "10"
.row.gy-3.justify-content-evenly.justify-content-md-start
  .col-auto
    %button.btn.btn-primary{ form: "edit_research_article_#{article.id}" }= "Save Notes"
  - if article.status == "new"
    .col-auto
      = form_for(article) do |f|
        = f.hidden_field(:status, value: "saved")
        = f.submit "Save For Later", class: "btn btn-primary"
  - if article.status == "new" || article.status == "saved"
    .col-auto
      = form_for(article) do |f|
        = f.hidden_field(:status, value: "read")
        = f.submit "Mark As Read", class: "btn btn-primary"
  - if article.status == "read"
    .col-auto
      = form_for(article) do |f|
        = f.hidden_field(:status, value: "saved")
        = f.submit "Mark Unread", class: "btn btn-primary"
  .col-auto
    %button.btn.btn-primary{type: "button", data: { bs: { toggle: "modal", target: "#notInterestedArticle-#{article.id}" } } }= "Not Interested"
    .modal{ id: "notInterestedArticle-#{article.id}", tabindex: "-1" }
      .modal-dialog
        .modal-content
          .modal-body
            %p= "Are you sure you want to mark <em>#{article.title}</em> as 'Not Interested'? You will not see this article again.".html_safe
            .row.gy-3
              .col-auto
                = form_for(article) do |f|
                  = f.hidden_field(:status, value: "not interested")
                  = f.submit "Not Interested", class: "btn btn-dark"
              .col-auto
                %button.btn.btn-dark{ data: { bs: { dismiss: "modal" } } }= "Cancel"
  .col-auto
    %a.btn.btn-primary{ href: article.url, role: "button"}= "Read Full Article"

app/views/shared/_research_article_headers.html.haml
.row= article.title
.row.mt-3.text-muted= article.date_published

app/views/shared/_topics_index.html.haml
- if (category == "research" && !current_user.visited_research_topics) || (category == "news" && !current_user.visited_news_topics)
  .d-none#showInfoModal
- if category == "research"
  %h1.mx-auto.text-center.mt-3= "Research"
  %h4.mx-auto.text-center.my-4= "Thank you to arXiv for use of its open access interoperability."
- elsif category == "news"
  %h1.mx-auto.text-center.mt-3= "News"
  %h4.mx-auto.text-center.my-4= "Thank you to Media Stack for use of its free API."  
.container-md.mx-auto.d-flex.flex-column.justify-content-center.d-md-block
  %h3.mb-3= "Requests Used Today: #{current_user.todays_query_count(category)}"
  %h3.mb-5= "Requests Remaining Today: #{25 - current_user.todays_query_count(category)}"
  %button.mb-3.fs-5.btn.btn-primary.mx-auto{data: { bs: { toggle: "modal", target: "#addTopicModal" } } }= "Add Topic"
  .modal#addTopicModal{ tabindex: "-1", aria: { labelledby: "topicModalLabel", hidden: "true" } }
    .modal-dialog
      .modal-content
        .modal-header
          %h5.modal-title#topicModalLabel= "New Topic"
          %button.btn-close{ type: "button", data: { bs: { dismiss: "modal" } }, aria: { label: "Close" } }
        .modal-body
          = form_for Topic.new, url: '/topics' do |f|
            .mb-3
              = f.label :title, class: "form-label"
              = f.text_field :title, class: "form-control mb-3"
              = f.label :search_terms, "Search Terms (add up to 5)", class: "form-label"
              - 5.times do |n|
                = f.text_field :search_terms, value: "",  id: "searchTerm#{n}", name: "topic[search_terms][]", class: "form-control mb-2"
              = f.hidden_field :category, value: category 
              = f.submit "Add", class: "btn btn-primary"
  - current_user.topics.where(category: category).each.with_index do |topic, topic_number|
    .container-md.mb-3.px-0.py-3.border-top.border-dark.border-3.d-flex.flex-column.justify-content-center.d-md-block
      .modal{id: "topic-#{topic_number}-SearchTermModal", tabindex: "-1", aria: { labelledby: "searchTermModalLabel", hidden: "true" } }
        .modal-dialog
          .modal-content
            .modal-header
              %h5.modal-title#searchTermModalLabel= "New Search Term"
              %button.btn-close{ data: { bs: { dismiss: "modal" } }, aria: { label: "Close" } }
            .modal-body
              = form_for SearchTerm.new do |f|
                .mb-3
                  = f.label :term, "New Term For #{topic.title}", class: "form-label" 
                  = f.text_field :term, class: "form-control mb-3"
                  = f.hidden_field :topic_id, value: topic.id
                  = f.submit "Add", class: "btn btn-primary"
      %h2.text-center.text-md-start.mb-3= topic.title
      .row.justify-content-center.justify-content-md-start
        .col-md-auto.col-12
          %h4.text-center= "Search Terms:"
        .col-9 
          .row.gy-2.justify-content-center.justify-content-md-start
            - topic.search_terms.each do |term|
              .col-auto
                = form_for term, method: :delete  do |f|
                  %p.fs-5.text-dark
                    = term.term
                    %button.btn-close(type="submit" aria-label="Close")
            .col-auto
              %button.btn.btn-primary{ data: { bs: { toggle: "modal", target: "#topic-#{topic_number}-SearchTermModal" } } }= "Add Term"
      - if category == "research" && topic.articles.where(status: "new").length >= 10
        = render 'shared/no_new_research_articles_modal'
      - else
        = form_tag('/articles') do
          = hidden_field_tag 'topic_id', topic.id
          %button.btn.btn-primary.mt-3= "Get New Articles"
      - if topic.articles.length == 0
        %h4.p-3.my-3.bg-secondary= "There were no articles found for your search."
      - else
        .accordion.my-3.bg-light{ id: "topic-#{topic_number}-articlesAccordion" }
          .accordion-item
            %h2.accordion-header{ id: "topic-#{topic_number}-new" }
              %button.accordion-button.collapsed{ type: "button", data: { bs: { toggle: "collapse", target: "#topic-#{topic_number}-newArticlesCollapse" } }, aria: { expanded: "false", controls: "topic-#{topic_number}-newArticlesCollapse" } }
                = "New"
                %span.badge.bg-primary.ms-3= topic.articles.where(status: "new").length 
                - if category == "research" && topic.research_new_today_count > 0
                  %span.ms-3.text-success= "#{topic.research_new_today_count} New Today"
                - if category == "news" && topic.news_new_today_count > 0
                  %span.ms-3.text-success= "#{topic.news_new_today_count} New Today"
            .collapse.accordion-collapse{ id: "topic-#{topic_number}-newArticlesCollapse" , aria: { labelledby: "topic-#{topic_number}-new" } }
              .accordion-body
                .accordion{ id: "topic-#{topic_number}-newAccordion" }
                  - if topic.articles.where(status: "new").length == 0
                    %p= "It looks like there aren't any articles you haven't seen before. Try adding a new search term for more results."
                  - topic.articles.where(status: "new").each.with_index do |article, article_number|
                    .accordion-item
                      %h2.accordion-header{ id: "topic-#{topic_number}-newArticle-#{article_number}" }
                        %button.accordion-button.collapsed{ type: "button", data: { bs: { toggle: "collapse", target: "#topic-#{topic_number}-newArticle-#{article_number}-collapse" } }, aria: { expanded: "false", controls: "topic-#{topic_number}-newArticle-#{article_number}-collapse" } }
                          .container
                            - if category == "research"
                              = render "shared/research_article_headers", article: article
                            - elsif category == "news"
                              = render "shared/news_article_headers", article: article
                      .collapse.accordion-collapse{ id: "topic-#{topic_number}-newArticle-#{article_number}-collapse", aria: { labelledby: "topic-#{topic_number}-newArticle-#{article_number}" } }
                        .accordion-body
                          = render 'shared/article', article: article
          .accordion-item
            %h2.accordion-header{ id: "topic-#{topic_number}-saved" }
              %button.accordion-button.collapsed{ type: "button", data: { bs: { toggle: "collapse", target: "#topic-#{topic_number}-savedArticlesCollapse" } }, aria: { expanded: "false", controls: "topic-#{topic_number}-savedArticlesCollapse" } }
                = "Saved"
                %span.badge.bg-primary.ms-3= topic.articles.where(status: "saved").length 
            .collapse.accordion-collapse{ id: "topic-#{topic_number}-savedArticlesCollapse", aria: { labelledby: "topic-#{topic_number}-saved" } }
              .accordion-body
                .accordion.bg-light{ id: "topic-#{topic_number}-savedAccordion" }
                  - topic.articles.where(status: "saved").each.with_index do |article, article_number|
                    .accordion-item
                      %h2.accordion-header{ id: "topic-#{topic_number}-savedArticle-#{article_number}" }
                        %button.accordion-button.collapsed{ type: "button", data: { bs: { toggle: "collapse", target: "#topic-#{topic_number}-savedArticle-#{article_number}-collapse" } }, aria: { expanded: "false", controls: "topic-#{topic_number}-savedArticle-#{article_number}-collapse" } }
                          .container
                            - if category == "research"
                              = render "shared/research_article_headers", article: article
                            - elsif category == "news"
                              = render "shared/news_article_headers", article: article
                      .collapse.accordion-collapse{ id: "topic-#{topic_number}-savedArticle-#{article_number}-collapse", aria: { labelledby: "topic-#{topic_number}-savedArticle-#{article_number}" } }
                        .accordion-body
                          = render 'shared/article', article: article
          .accordion-item
            %h2.accordion-header{ id: "topic-#{topic_number}-read" }
              %button.accordion-button.collapsed{ type: "button", data: { bs: { toggle: "collapse", target: "#topic-#{topic_number}-readArticlesCollapse" } }, aria: { expanded: "false", controls: "topic-#{topic_number}-readArticlesCollapse" } }
                = "Read"
                %span.ms-3.badge.bg-primary= topic.articles.where(status: "read").length  
            .collapse.accordion-collapse{ id: "topic-#{topic_number}-readArticlesCollapse", aria: { labelledby: "topic-#{topic_number}-read" } }
              .accordion-body
                .accordion{ id: "topic-#{topic_number}-readAccordion" }
                  - topic.articles.where(status: "read").each.with_index do |article, article_number|
                    .accordion-item
                      %h2.accordion-header{ id: "topic-#{topic_number}-readArticle-#{article_number}" }
                        %button.accordion-button.collapsed{ type: "button", data: { bs: { toggle: "collapse", target: "#topic-#{topic_number}-readArticle-#{article_number}-collapse" } }, aria: { expanded: "false", controls: "topic-#{topic_number}-readArticle-#{article_number}-collapse" } }
                          .container
                            - if category == "research"
                              = render "shared/research_article_headers", article: article
                            - elsif category == "news"
                              = render "shared/news_article_headers", article: article
                      .collapse.accordion-collapse{ id: "topic-#{topic_number}-readArticle-#{article_number}-collapse", aria: { labelledby: "topic-#{topic_number}-readArticle-#{article_number}" } }
                        .accordion-body
                          = render 'shared/article', article: article
      %button.btn.btn-dark.mx-auto{type: "button", data: { bs: { toggle: "modal", target: "#deleteTopic-#{topic_number}" } } }= "Delete Topic"
      .modal{ id: "deleteTopic-#{topic_number}", tabindex: "-1" }
        .modal-dialog
          .modal-content
            .modal-body
              %p= "Are you sure you want to delete the topic <em>#{topic.title}</em>? This cannot be undone.".html_safe
              .row.gy-3
                .col-auto
                  = form_for topic, method: :delete do |f|
                    = f.submit "Yes", class: "btn btn-dark" 
                .col-auto
                  %button.btn.btn-dark{ data: { bs: { dismiss: "modal" } } }= "No"
- if category == "research"
  = render 'shared/info_modal_research'
- elsif category == "news"
  = render 'shared/info_modal_news'