config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'pages#index', as: 'home'

	resources :articles, only: [:update, :create]
  get '/research', to: 'topics#research_index', as: 'research'
  get '/news', to: 'topics#news_index', as: 'news'
  resources :topics, only: [:create, :update, :destroy]
  resources :search_terms, only: [:create, :destroy]

  resources :users, only: [:create, :update]
  get '/new_account', to: 'users#new', as: 'new_account'
  get '/my_account', to: 'users#show', as: 'my_account'
  get '/edit_account', to: 'users#edit', as: 'edit_account'
  get '/forgot_password', to: 'users#forgot_password', as: 'forgot_password'
  post '/forgot_password', to: 'users#forgot_password'
  get '/reset_password/:token', to: 'users#reset_password', as: 'reset_password'
  post '/reset_password', to: 'users#reset_password'
  get '/reset_password_confirmation', to: 'users#reset_password_confirmation', as: 'reset_password_confirmation'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get 'active', to: 'sessions#active'
  get 'timeout', to: 'sessions#timeout'

  # Error routes
  get "/404", to: "errors#error_404"
  get "/422", to: "errors#error_422"
  get "/500", to: "errors#error_500"
end

app/views/pages/index.html.haml
.row.justify-content-around
  .col.col-md-5
    .w-100.d-flex.justify-content-end
    %h1.text-center.text-dark.mt-4= "Welcome To InfoCompass"
    %h4.text-center.text-dark.mt-3= "Find your way to the information you need"
    .container.w-75.py-3
      = # Image downloaded from https://pixabay.com/vectors/compass-map-navigation-wind-rose-146166/
      = # Created by user OpenClipart-Vectors and available to use for free
      = image_tag "compass.png", alt: "compass", class: "img-fluid"
    .container.w-100.px-5
      .row.justify-content-between.mt-4 
        .col-auto  
          = link_to "Sign Up", new_account_path, class: "btn btn-primary fs-5"
        .col-auto
          = link_to "Login", login_path, class: "btn btn-primary fs-5"
  .w-100.d-block.d-md-none.mb-4
  .col.col-md-5
    = # Image downloaded from https://www.pikpng.com/transpng/JhRwob/, they did not mention an artist or requirement to give credit
    = image_tag "globe.png", alt: "people extracting data from the earth", class: "img-fluid mt-5 me-3"
.w-100.d-block.d-sm-none.pb-4
.container-fluid.m-0.mt-5.pb-3.pt-2.bg-secondary
  %h4.text-center.text-dark.my-3= "Powered By"
  .row.px-4.justify-content-around
    .col-2.col-lg-1
      = image_tag "ruby.png", alt: "Ruby logo", class: "img-fluid"
    .col-2.col-lg-1
      = image_tag "rails.png", alt: "Ruby on Rails logo", class: "img-fluid"
    .col-2.col-lg-1
      = image_tag "bootstrap.png", alt: "Bootstrap logo", class: "img-fluid"
    .w-100.d-block.d-md-none.mb-3
    .col-2.col-lg-1
      = image_tag "haml.png", alt: "Haml logo" , class: "img-fluid"
    .col-2.col-lg-1
      = image_tag "postgresql.png", alt: "PostgreSQL logo", class: "img-fluid"
    .col-2.col-lg-1
      = image_tag "arxiv.png", alt: "Arxiv logo", class: "img-fluid"
= render 'shared/info_modal_main'

app/views/pages/old_index.html.haml
%h1.text-center.text-dark.mt-4= "Welcome To InfoCompass"
%h4.text-center.text-dark.mt-3= "Find your way to the information you need"
.container.w-25
  = image_tag "compass.png", alt: "compass", class: "img-fluid"
.w-100.d-block.d-sm-none.pb-3
.container.w-50
  .row.justify-content-between.mt-4 
    .col-auto  
      = link_to "Sign Up", new_user_path, class: "btn btn-primary fs-5"
    .col-auto
      = link_to "Login", login_path, class: "btn btn-primary fs-5"
.w-100.d-block.d-sm-none.pb-4
.container-fluid.m-0.mt-5.pb-3.pt-2.bg-secondary
  %h4.text-center.text-dark.my-3= "Powered By"
  .row.px-4.justify-content-around
    .col-2.col-lg-1
      = image_tag "ruby.png", alt: "Ruby logo", class: "img-fluid"
    .col-2.col-lg-1
      = image_tag "rails.png", alt: "Ruby on Rails logo", class: "img-fluid"
    .col-2.col-lg-1
      = image_tag "bootstrap.png", alt: "Bootstrap logo", class: "img-fluid"
    .w-100.d-block.d-md-none.mb-3
    .col-2.col-lg-1
      = image_tag "haml.png", alt: "Haml logo" , class: "img-fluid"
    .col-2.col-lg-1
      = image_tag "postgresql.png", alt: "PostgreSQL logo", class: "img-fluid"
    .col-2.col-lg-1
      = image_tag "arxiv.png", alt: "Arxiv logo", class: "img-fluid"